spring:
  datasource:
    url: jdbc:mysql://13.124.242.194:3306/bmt_test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace

#LeeNamSoo 02.04 https사용을 위한 인증서
server:
  port: 8081
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/ssafy.p12
    key-store-password: ssafyssafy
    key-alias: ssafy
trust:
  store: classpath:keystore/ssafy.p12
  store.password: ssafyssafy
